### ISSUE TITLE
The Forwading to Etherpad/Ethercalc has been blocked.

### ISSUE THREAD

**Issue by Pisoko** [otetard/ownpad#33]
When I open the .pad there is the following error:

**The Forwading to Etherpad/Ethercalc has been blocked.**

My Etherpad runs on the same machine via docker available over http://servname:9001
Maybe I have to config my Etherpad?

To install Etherpad i used this docker:
https://hub.docker.com/r/tvelocity/etherpad-lite/

Greets from Germany

**Comment by otetard** [comment]
This error is displayed because (theoretically) the Etherpad URL mentioned in your `.pad` file doesn’t match the one defined in your Ownpad configuration.

Did you configured Ownpad and defined your Etherpad instance? Can you send me the content of you `.pad` file and the URL defined in Ownpad configuration please?

Olivier;

**Comment by otetard** [comment]
I can’t reproduce the bug. Feel free to reopen it if this issue is still valid.

Olivier;
