### ISSUE TITLE
HTTPS Error

### ISSUE THREAD

**Issue by Engineer-of-Stuff** [otetard/ownpad#51]
I set up Etherpad to run on HTTPS, since my Nextcloud site runs on it too. Etherpad works when I open it in the browser (outside of Nextcloud), but when launched from Nextcloud it will give the error:
`The Target-URL of this File does not match the allowed server. The Forwading [sic] to Etherpad/Ethercalc has been blocked.`

It the Nextcloud Etherpad settings my Etherpad Host is _https://192.168.0.37:9001_

Did I set up something wrong?

**Comment by otetard** [comment]
Thanks for the feedback! I think issue is similar to #33.

This message is displayed because the URL contained in your `.pad` document doesn’t match your configuration. In this case, you can’t open your document (maybe this behavior should be configurable…).

Is the content of your `.pad` file looks like that?

    [InternetShortcut]
    URL=https://192.168.0.37:9001/p/XXXXXX

Cheers,
Olivier;

**Comment by Engineer-of-Stuff** [comment]
So I reinstalled Nextcloud (had some issues with it) and the error went away. It now loads the document.

The .pad file now has the correct url.
`[InternetShortcut]
URL=https://192.168.0.37:9001/p/fTrBzRoyou6LeRfV`

**Comment by otetard** [comment]
Ok thanks, so I close this bug.
